### ISSUE TITLE
Backend service creation request

### ISSUE THREAD

**Issue by slashtechno** [hackclub/infra#102]
Desired service name: Event Showcase

HQ Project for the events team (cc @devenjadhav)

**Comment by grymmy** [comment]
Hey - I missed this one for quite a while, does this still need to be provisioned, or did you get someone else to do it?

**Comment by slashtechno** [comment]
It still needs to be provisioned, although the project it's for isn't production-ready yet.

**Comment by grymmy** [comment]
Please DM me on slack your email such that I can add u to heroku

**Comment by grymmy** [comment]
'graham' in slack

**Comment by grymmy** [comment]
Done, with you added as a collaborator with maintenance perms.
