### ISSUE TITLE
Investigate issues with HQ internet setup and config

### ISSUE THREAD

**Issue by grymmy** [hackclub/infra#2]
Bullet points from @zachlatta:

- Configuration is a bit of a mess
- Low speed / flakey connections in upstairs left call room
- Unifi interface should be looked / unused endpoints should be cleaned up
- Endpoints upstairs should be reset and configs checked

**Comment by grymmy** [comment]
@ma1ted took a pass at this about a month ago and improved reliability of our network significantly.  Keeping this open as there are probably follow-ups that should still be performed...

**Comment by grymmy** [comment]
Closing this as I believe @malted took a pass at HQ inet stuff a while ago.

**Comment by malted** [comment]
I did! Upstairs should be fixed too.
