### ISSUE TITLE
Sinerider Twitter Bot - Metric Spam

### ISSUE THREAD

**Issue by GalaxyGamingBoy** [hackclub/infra#20]
`stats.production.sinerider-twitter-bot` sends a metric with the URL parameter: `publishpuzzlepublishinginfo` which is a long parameter that contains a lz-encoded sinerider level json.

Example log:
```
26/10/2023 17:44:55 :: [console] Error creating stats_counts.production.sinerider-twitter-bot.web..http.response.post_publishpuzzlepublishinginfo=lvldata/500.wsp'
```

**Comment by grymmy** [comment]
@GalaxyGamingBoy FYI - if you don't feel like working on this please assign it back to me and I'll find a home or deal w/ it myself

**Comment by GalaxyGamingBoy** [comment]
Oh woops mb, I actually just need to push the change

**Comment by grymmy** [comment]
oh - heh - sweet

**Comment by grymmy** [comment]
This is not the proper home for this issue - also it is not a large (actual) issue at this point given upgrades to grafana disk space.
