### ISSUE TITLE
Unclear what the official sprig channels are

### ISSUE THREAD

**Issue by maxwofford** [hackclub/infra#23]
A user brought up a potential bug in #sprig on the slack today and I was looking to crosspost it to the official sprig development channel. While looking, I got a lot of suggestions:

<img width="718" alt="Screenshot 2023-11-08 at 15 41 19" src="https://github.com/hackclub/infra/assets/5891442/bbe86e0d-7f65-4c64-bbee-90ab123e0c0f">

From this list, it's very unclear where to get official support. The correct channel, #sprig-platform, is only the top result in the screenshot because I just joined it after searching through the other channels.

**Comment by grymmy** [comment]
I have also modified the topic of the Sprig channel to be explicit about its being the primary channel for the Sprig project.
