### ISSUE TITLE
Audit of Heroku Permissions

### ISSUE THREAD

**Issue by garyhtou** [hackclub/infra#24]
Let's perform an audit of user permissions on Heroku, especially the admin users. My goal is to reduce the number of admins to limit people who have access to ALL apps.

https://hackclub.slack.com/archives/C05SVRTCDGV/p1699482855663709

https://devcenter.heroku.com/articles/team-permissions
https://devcenter.heroku.com/articles/heroku-teams#managing-permissions
https://devcenter.heroku.com/articles/app-permissions

**Comment by grymmy** [comment]
@garyhtou Just setting expectations here - I likely will focus on this work in a couple of weeks...

**Comment by garyhtou** [comment]
Sounds good! Just give me a ping on Slack when you get around to it

**Comment by garyhtou** [comment]
FYI, I've looped @malted in to help with this and to provide some perspective from the HCB engineering team

**Comment by grymmy** [comment]
@garyhtou FYI - @malted and I just performed a heroku perms audit and removed 5 admins, 3 members, and a handful of inactive/invalid collabs.  We have manually inspected all users actually and believe that the remaining perms are valid and necessary for people to do their work.  We still have a couple of accounts that while we want to delete them, they need to be investigated a bit thoroughly to ensure nothing breaks.  When we resolve those, we'll mark this as closed.

**Comment by garyhtou** [comment]
Amazing! Thank you for your work on this

**Comment by grymmy** [comment]
Done quite some time ago.  Not moving forward with any more work re: this in the short term.
