### ISSUE TITLE
Nest team + DNS repo config changes

### ISSUE THREAD

**Issue by ajs256** [hackclub/infra#30]
Nest team **would like to have a subteam on GitHub** so we can be codeowners for the hackclub.app DNS - this, combined with **enabling required reviews for the DNS repo**, **adding CODEOWNERS to DNS**, and **giving said Nest team write access**, would allow us to manage the hackclub.app DNS without letting us change the other domains. The people that should be on the team are:
- Sam @polypixeldev
- Alex @alx-alexpark
- Reese @reesericci
- Me @ajs256

**Comment by grymmy** [comment]
https://github.com/orgs/hackclub/teams/nest/members

**Comment by grymmy** [comment]
> Here's what the CODEOWNERS could look like:
> 
> ```
> # https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners
> # Lowest matching rule takes precedence, so adding the infra team to every rule
> # ensures they will still be able to modify everything if need be
> 
> * @hackclub/infra
> 
> # Nest
> hackclub.app.yaml @hackclub/nest @hackclub/infra
> 
> # HCB
> bank.engineering.yaml @hackclub/hcb @hackclub/infra 
> ```

@ajs256 you should be able to author this PR yourself now that I've added the team.  Feel free to ping me for review.

**Comment by grymmy** [comment]
Provisioned team and provided move-forward guidance.
