### ISSUE TITLE
Repo creation request

### ISSUE THREAD

**Issue by aicoder2009** [hackclub/infra#32]
Desired repository name: Hackpi
(Note - please use github usernames) Maintainer(s): @aicoder2009, @ansh3108, @itsimpeccable, @AverseABFun, @kcoderhtml, @ajs256, @karmanyaahm, @polypixeldev, @SerenityUX, @V205Arduino

**Comment by V205Arduino** [comment]
Why does this need to be a repo under the Hack Club  organization?
Why not a personal one?

**Comment by aicoder2009** [comment]
it is for hackclubbers right, therefore it should be under hackclub , its under hackclub

**Comment by V205Arduino** [comment]
There are many projects that HackClubbers run, most of them use a personal repo

**Comment by aicoder2009** [comment]
alright i will make a personal one and close this request with this comment

**Comment by V205Arduino** [comment]
Ok!
thanks

**Comment by itsimpeccable** [comment]
Just saw this

9 Oca 2024 Sal 01:51 tarihinde V205 ***@***.***> şunu yazdı:
