### ISSUE TITLE
Repo creation request

### ISSUE THREAD

**Issue by sahitid** [hackclub/infra#33]
Desired repository name: <blossom>
(Note - please use github usernames) Maintainer(s): <sahitid>

**Comment by grymmy** [comment]
@sahitid I need more information please fill out the description w/ what name you want for the repo and whom should be added as a collaborator.

**Comment by sahitid** [comment]
Sorry! I thought I did.

Name: blossom
Maintainers: sahitid

**Comment by grymmy** [comment]
Created hackclub/blossom as requested.
