### ISSUE TITLE
Allowing adding people to hackclub repos

### ISSUE THREAD

**Issue by AverseABFun** [hackclub/infra#42]
I recently got [hackclub/asmgame](https://github.com/hackclub/asmgame) and want to add someone to it. I think it'd be nice to be able to do this myself, but I'd like to at least have @46-HA added to it, as we are working on it together. I'm also sure I'm not alone in wanting to be able to manually add users myself to hackclub repos.

**Comment by JosiasAurel** [comment]
why not just have them contribute to the project by sending in PRs?

**Comment by AverseABFun** [comment]
> why not just have them contribute to the project by sending in PRs?

Yes, that's what I'm currently doing, and I suppose that works, I'm just more used to adding someone to the repo instead of sending in PRs.

**Comment by AverseABFun** [comment]
> I have increased your perms from maintain -> admin. You should be able to add collabs now yourself (to this project)

Thank you!
