### ISSUE TITLE
Request github admin support

### ISSUE THREAD

**Issue by snoglobe** [hackclub/infra#46]
What are you blocked by? <_please describe your issue, and why you need a specific action from a Github admin_>

**Note - please limit your issue submissions to things that you very specifically need Github admin permissions.  This is, unfortunately, not an open invitation to debug your project...**

Trying to re-open an issue on the Sprig repo, and also want to be able to review PRs

**Comment by grymmy** [comment]
@snoglobe - I have provided you triage access to Sprig.  This allows you to assign and manipulate issues.  Please feel free to review PRs in Sprig regardless of your current write access - once we see a track record of good reviews we can escalate your access as is reasonable.
![Screenshot 2024-03-29 at 9 32 01 AM](https://github.com/hackclub/infra/assets/43505167/7006cc00-ce9d-4d1e-b832-0476ca340560)
