### ISSUE TITLE
Add Nest admins to hackclub/nest team

### ISSUE THREAD

**Issue by polypixeldev** [hackclub/infra#47]
The current Nest admins are now:
- @alx-alexpark
- @cskartikey
- @aboutdavid
- @reesericci
- @polypixeldev

These people should be on the @hackclub/nest team, so @aboutdavid and @cskartikey need to be added, and @ajs256 should be removed.

**Comment by grymmy** [comment]
Done.
<img width="568" alt="Screenshot 2024-03-28 at 4 15 58 PM" src="https://github.com/hackclub/infra/assets/43505167/ec92e679-16af-46f6-8d28-02bc83003831">
