### ISSUE TITLE
Repo creation request

### ISSUE THREAD

**Issue by Arpan-206** [hackclub/infra#53]
Desired repository name: open-ai-token
(Note - please use github usernames) Maintainer(s): <@Arpan-206>

**Comment by Arpan-206** [comment]
We're redoing the OpenAi Token to include reporting, access controls etc with a new db and stuff.

**Comment by grymmy** [comment]
![Screenshot 2024-04-10 at 10 15 03 AM](https://github.com/hackclub/infra/assets/43505167/738657fe-0932-45e9-9fba-c9f01b79778c)
