### ISSUE TITLE
Request github admin support / Add 9pfs to Nest admin team 

### ISSUE THREAD

**Issue by aboutdavid** [hackclub/infra#58]
What are you blocked by? <_please describe your issue, and why you need a specific action from a Github admin_>

**Note - please limit your issue submissions to things that you very specifically need Github admin permissions.  This is, unfortunately, not an open invitation to debug your project...**

@hello-smile6 (9pfs on slack, U05FHGVJ3U7) needs to be added to the Nest GitHub team as he is now a Nest admin.

**Comment by jaspermayone** [comment]
@grymmy you did this already yea?

**Comment by jaspermayone** [comment]
i seem to remember you telling me you had and that it just needed response and to be closed

**Comment by grymmy** [comment]
Yeah this was done a while ago, sorry for not closing this promptly.
