### ISSUE TITLE
Access to Clubs Team Repos

### ISSUE THREAD

**Issue by Arpan-206** [hackclub/infra#59]
What are you blocked by? 
Not having access to the clubs team repos

Please give me write access to toolbox, workshops, jams, and other clubs team repositories.

**Comment by grymmy** [comment]
Yourself, Sahiti and Jasper have been added to [bouncers](https://github.com/orgs/hackclub/teams/bouncers).  This provides maintainer-level access to:
- toolbox
- leaders-newsletter
- application-viewer
- jams
- directory
- summit
- the-trail
- turnover
- apply
- slackapolt
- pizza-fund
- workshops
