### ISSUE TITLE
Airtable - Move to using personal access tokens (DUE 01/31/24)

### ISSUE THREAD

**Issue by grymmy** [hackclub/infra#7]
@maxwofford mentioned there may be a significant # of services that need to be moved to the new auth scheme, the most notable being [Airbridge](https://github.com/hackclub/airbridge)

This is the disclaimer from airtable:
<img width="1670" alt="Screenshot 2023-03-31 at 2 52 25 PM" src="https://user-images.githubusercontent.com/43505167/229205841-c82980fe-d72f-4a4b-82ae-fb7e54f5cabe.png">

**Comment by grymmy** [comment]
Relevant info:
<img width="510" alt="Screenshot 2023-10-20 at 11 29 21 AM" src="https://github.com/hackclub/infra/assets/43505167/b04b0911-2e13-4041-8771-693208db0da8">

**Comment by maxwofford** [comment]
Take back what I said about HCB– https://github.com/hackclub/hcb/pull/5127 is going to change this so we don't need to support it

**Comment by JosiasAurel** [comment]
I replaced the `AIRTABLE_API_KEY` with a new Personal Access Token from Airtable with read permissions.

**Comment by grymmy** [comment]
@JosiasAurel just wondering - is just read perms enough?  aren't there write use-cases in airbridge?

**Comment by JosiasAurel** [comment]
There are however they require passing an authKey. The key that is passed as env is used for reading publicly accessible info. Please confirm @maxwofford
