### ISSUE TITLE
Yet another mini-book about computers

### ISSUE THREAD

**Issue by ILyesMk2** [hackclub/infra#79]
Desired repository name: RAM-a-thon
Maintainer(s): @ILyesMk2

**Comment by grymmy** [comment]
> Desired repository name: RAM-a-thon Maintainer(s): @ILyesMk2

Can you please develop this independently, and then we could promote it to a HC repo once something is actually done?  Plz reach out to me on Hack Club's slack if you want to discuss this further.

**Comment by ILyesMk2** [comment]
Sure, i will drop you a line on slack.
