### ISSUE TITLE
Slash-Z - JWT deprecation (DUE: 09/01/2023)

### ISSUE THREAD

**Issue by grymmy** [hackclub/infra#8]
https://hackclub.slack.com/archives/C0179FFFRRV/p1686593443262159

**Comment by Hk669** [comment]
hey @grymmy ! I'm interested in contributing, is there anything I can work on?
language: python

**Comment by grymmy** [comment]
> hey @grymmy ! I'm interested in contributing, is there anything I can work on? language: python

Hi @Hk669 !  Sure, there are lots of ways you can contribute, any chance you could contact me on HC Slack (@graham) and we could discuss?

Quite separately - marking this issue as fixed/closed as we finished the work on this last week...
