### ISSUE TITLE
Repo creation request

### ISSUE THREAD

**Issue by revaga** [hackclub/infra#81]
Desired repository name: golden
(Note - please use github usernames) Maintainer(s): <revaga, kriaga259, audreyolafz>

**Comment by revaga** [comment]
for an [Athena](athena.hackclub.com) event

**Comment by JosiasAurel** [comment]
Just created the new repository under [hackclub/golden](https://github.com/hackclub/golden) and invited the maintainers.

**Comment by revaga** [comment]
can we make the repo public? thank you

**Comment by JosiasAurel** [comment]
I've just made the repository public
