### ISSUE TITLE
Special Activities Division GitHub User Group

### ISSUE THREAD

**Issue by aramshiva** [hackclub/infra#84]
Special Activities Division needs access to event related repos like the [`hackclub/Arcade-Game-Jam`](https://github.com/hackclub/Arcade-Game-Jam). If possible can an github group be made with the following github users and access to edit the Arcade Jam Repo.
```
aramshiva
Arpan-206
DillonB07
AlicornEagle11
evan-gan
techpixel
michelle12349502039
sahitid
cskartikey
radioblahaj
```

**Comment by EmperorNumerius** [comment]
Can I be added too?
username is Emperor Numerius and im part of the organizing team for the Arcade Jam and future hack club game jam's

**Comment by aramshiva** [comment]
You can but not the special activities division GitHub group

**Comment by JosiasAurel** [comment]
I've created the team and added it to the Arcade-Game-Jam repository
