### ISSUE TITLE
Upgrade OnBoard Live VPS to a dedicated server

### ISSUE THREAD

**Issue by MichaByte** [hackclub/infra#87]
@grymmy and I discussed this over Slack. He said he will take care of this next week, but asked me to open an infra ticket. The current OnBoard Live server is a Hetzner VPS with dedicated vCPU cores, which are better than shared ones but worse than dedicated "real" cores. Hetzner has many servers [on auction](https://www.hetzner.com/sb/) for about $9 more per month, while providing 64GB RAM, a desktop class Intel CPU, and far more storage save recordings (up to 1TB, as pictured.) This would allow for more concurrent streams, higher reliability (there's already been one crash due to lack of available CPU resources) and better stream quality due to increased network capacity. Thank you!

![image](https://github.com/user-attachments/assets/9b9b2e81-8d4f-4971-ac81-7d91b607ed61)
This exact server listing will expire by next week, but I've been checking and there are always similar ones on the auction page.

**Comment by grymmy** [comment]
In process.  Will update this ticket if/when we win auction.  Plz be prepared to do a test so that we can ensure this upgrade is indeed an actual upgrade and improves perf of onboard live.

**Comment by grymmy** [comment]
This was completed some time ago.
