### ISSUE TITLE
Repo creation request

### ISSUE THREAD

**Issue by arungeorgesaji** [hackclub/infra#95]
Desired repository name: hackclub-discord-bot
(Note - please use github usernames) Maintainer(s): @arungeorgesaji

**Comment by arungeorgesaji** [comment]
The repo is for a Discord bot designed for Hack Club members, enabling quick setup and collaboration features,along with other features which allows club members to easily work on things like the club site etc.

**Comment by grymmy** [comment]
Can you please link the code to the discord bot first?  I have very little context here re: what this discord bot would do.  I would rather not create a repo such as this without a clear understanding of what's going in it, what the project is

**Comment by arungeorgesaji** [comment]
I havent really worked on it yet,so closing the issue for now will reopen it once I have worked on it and the repo is ready for approval...

Thanks for your time....
